version: '3.7'
services:
  mongodb_container:
    image: mongo:latest
    ports:
      - 27017:27017
    volumes:
      - ./data:/data/db
  discord_bot:
    build: .
    volumes:
      - ./.env:/usr/src/app/.env