name: Deploy to Raspberry Pi

on:
  push:
    branches:
      - master 

jobs:
  deploy:
    runs-on: self-hosted 

    steps:
      - name: Run bot
        run: |
          git pull
          go build
          ./onoge
        working-directory: /home/jonogoh/Documents/projects/onoge
