name: Onoge Workflow

on:
  push:
    branches:
      - master 

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Log in to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      - name: Set up QEMU
        uses: docker/setup-qemu-action@v3

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Build and push
        uses: docker/build-push-action@v6
        with:
          context: .
          push: true
          tags: jonogoh/onoge:latest
          platforms: linux/arm64/v8

      - name: SSH into Raspberry Pi and run new Docker image
        uses: appleboy/ssh-action@v1.1.0
        with:
          host: ${{ secrets.PI_HOST }}
          username: ${{ secrets.PI_USERNAME }}
          password: ${{ secrets.PI_PASSWORD }}
          script: |
            docker pull jonogoh/onoge:latest
            docker stop onoge-bot || true
            docker rm onoge-bot || true
            docker run -d --name onoge-bot -e DISCORD_TOKEN=${{ secrets.DISCORD_TOKEN }} jonogoh/onoge:latest