name: Deploy to Raspberry Pi

on:
  push:
    branches:
      - master  # Trigger on push to the main branch

jobs:
  deploy:
    runs-on: self-hosted  # This targets your self-hosted runner

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Go
        uses: actions/setup-go@v4
        with:
          go-version: '1.20'  # Replace with the version you're using

      - name: Build project
        run: |
          go build

      - name: Stop existing process (if any)
        run: |
          pkill -f onoge || echo "No running process to stop"

      - name: Run program
        run: |
          nohup ./onoge &  # Run in the background
