name: Deploy to Raspberry Pi

on:
  push:
    branches:
      - main  # Adjust if you want to deploy from another branch

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up SSH
        uses: webfactory/ssh-agent@v0.7.0
        with:
          ssh-private-key: ${{ secrets.PI_SSH_KEY }}

      - name: Copy files to Raspberry Pi
        run: |
          rsync -avz --delete . ${{ secrets.PI_USER }}@${{ secrets.PI_HOST }}:/home/${{ secrets.PI_USER }}/Documents/projects/onoge
